<WaistSlider>:
	orientation:'horizontal'
    min:10
	max:100
	value:10
	
<ShoulderSlider>:
	orientation:'horizontal'
    min:50
	max:140
	value:100
	
<ElbowSlider>:
	orientation:'horizontal'
	min:50
	max:170
	value:110

<WristUpDownSlider>:
	orientation:'horizontal'
	min:10
	max:150
	value:130

<WristTurnSlider>:
	orientation:'horizontal'
	min:10
	max:150
	value:150

<ClawSlider>:
	orientation:'horizontal'
	min:80
	max:150
	value:100
